#' A gt Theme Generated by quartomonothemer
#'
#' @param data A gt object
#' @param table.width Table Width
#' @param table.font.size Base font size
#' @param table.font.names Base font name
#' @param ... `gt::tab_options` options
#'
#' @return A gt theme
#' @export
#'

gt_theme_quarto <- function(data,
                            table.width = NULL,
                            table.font.names = NULL,
                            table.font.size = NULL,
                            ...) {

  table.width <- ifelse(is.null(table.width),
                        quartomonothemer_env$width_table, table.width)
  table.font.names <- ifelse(is.null(table.font.names),
                             quartomonothemer_env$font_text_table,
                             table.font.names)
  table.font.size <- ifelse(is.null(table.font.size),
                            quartomonothemer_env$size_font_table,
                            table.font.size)

  data |>
    gt::tab_options(
      table.width = table.width,
      table.font.names = table.font.names,
      table.font.size = table.font.size,
      column_labels.font.weight = "bold",
      ...
    )
}
